name: Update API file in repository
on: push
#  push:
#    branches:
#    - '!master'
#    paths:
#    - 'django-server/**'
#    - '.github/workflows/api_file_update.yaml'

jobs:
  build:
    name: Get the API file and create PR with it
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
#        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
      - name: Update API file
        run: |
          ls -R
          cd ./specs
          if wget https://eaterslab.herokuapp.com/api.yaml -O api_update.yaml; then
            rm -rf api.yaml
            mv api_update.yaml api.yaml
          fi
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update API file
          title: 'Update API file'
          body: |
            specs/api.yaml updated based on server newest version
          labels: django, automated, documentation
          assignees: avan1235
          reviewers: avan1235 kantoniak Rhantolq
          draft: false
          branch: workflow/api-update
